version: '3.8'

services:
  api:
    image: cmapss-predictive-maintenance-fastapi
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: rul_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models 
      - ./config.yaml:/config.yaml
    networks:
      - rul_network

networks:
  rul_network:
    driver: bridge